/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Interfaces.CRUD.Estudiantes;

/**
 *
 * @author Tecnico Superior
 */
public class CONFIGURACIÓN extends javax.swing.JFrame {

    /**
     * Creates new form CONFIGURACIÓN
     */
    public CONFIGURACIÓN() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BTN_Estudiantes = new javax.swing.JButton();
        Btn_obtenerReporte = new javax.swing.JButton();
        BTN_inicio = new javax.swing.JButton();
        Label_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITEC Votaciones / Admin");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_Estudiantes.setText("Crear Estudiante");
        BTN_Estudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EstudiantesActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_Estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        Btn_obtenerReporte.setText("Obtener Reporte");
        Btn_obtenerReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_obtenerReporteActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_obtenerReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        BTN_inicio.setText("Volver");
        BTN_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 40));

        Label_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/Fondo.jpg"))); // NOI18N
        jPanel1.add(Label_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 0, 670, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_EstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EstudiantesActionPerformed
        Estudiantes ITF = new Estudiantes();
        ITF.setVisible(true);
        ITF.setResizable(false);
        ITF.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_BTN_EstudiantesActionPerformed

    private void BTN_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_inicioActionPerformed

        INICIO in = new INICIO();
        in.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BTN_inicioActionPerformed

    private void Btn_obtenerReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_obtenerReporteActionPerformed

        
        Reporte Freport = new Reporte();
        Freport.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_Btn_obtenerReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CONFIGURACIÓN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CONFIGURACIÓN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CONFIGURACIÓN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CONFIGURACIÓN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONFIGURACIÓN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Estudiantes;
    private javax.swing.JButton BTN_inicio;
    private javax.swing.JButton Btn_obtenerReporte;
    private javax.swing.JLabel Label_Fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
