/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static javafx.application.Platform.exit;
import javax.swing.ImageIcon;

/**
 *
 * @author Tecnico Superior
 */
public class INICIO extends javax.swing.JFrame {

    /**
     * Creates new form INICIO
     */
    public INICIO() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
       try {
            this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/icono6.png")).getImage());
        } catch (Exception e) {
            System.out.print(e);
        }
            
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTAdministrador = new javax.swing.JButton();
        BTN_Ingresar = new javax.swing.JButton();
        Label_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITEC Votaciones");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Desarrollado Por:  Tecnica Desarrollo de Software 11°  Jornada Tarde");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        BTAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        BTAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/BTAyuda2.png"))); // NOI18N
        BTAdministrador.setBorder(null);
        BTAdministrador.setBorderPainted(false);
        BTAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAdministradorActionPerformed(evt);
            }
        });
        jPanel1.add(BTAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        BTN_Ingresar.setBackground(new java.awt.Color(0, 255, 102));
        BTN_Ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/BTIngresar_1.png"))); // NOI18N
        BTN_Ingresar.setBorder(null);
        BTN_Ingresar.setBorderPainted(false);
        BTN_Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_Ingresar.setOpaque(false);
        BTN_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 160, -1));

        Label_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/Pag Principal.jpg"))); // NOI18N
        Label_Fondo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Label_Fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Label_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 960, 642));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAdministradorActionPerformed
        CONFIGURACIÓN ITF = new CONFIGURACIÓN();
        ITF.setVisible(true);
        ITF.setResizable(false);
        this.setVisible(false);


    }//GEN-LAST:event_BTAdministradorActionPerformed

    private void BTN_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_IngresarActionPerformed
        BTN_Ingresar.setEnabled(false);
        
        
        SlectEstudiante ITF2 = new SlectEstudiante();
        
        
        ITF2.setVisible(true);
        ITF2.setResizable(false);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_IngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INICIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAdministrador;
    private javax.swing.JButton BTN_Ingresar;
    private javax.swing.JLabel Label_Fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
