/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import VOTO.V_Estudiante;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Tecnico Superior
 */
public class Personero extends javax.swing.JFrame {
 private final V_Estudiante VP;
 
    public Personero() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/icono6.png")).getImage());
        } catch (Exception e) {
        }
        VP= new V_Estudiante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BTcandidato1 = new javax.swing.JButton();
        BTcandidato2 = new javax.swing.JButton();
        BTcandidato3 = new javax.swing.JButton();
        BTVotoenblanco = new javax.swing.JButton();
        Label_candidato1 = new javax.swing.JLabel();
        Label_Gradocandidato1 = new javax.swing.JLabel();
        Label_candidato2 = new javax.swing.JLabel();
        Label_Votoenblanco = new javax.swing.JLabel();
        Label_Gradocandidato2 = new javax.swing.JLabel();
        Label_candidato3 = new javax.swing.JLabel();
        Label_Gradocandidato3 = new javax.swing.JLabel();
        Label_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITEC Votaciones /  Personero");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1309, 960));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Presiona la foto del candidato que deseas que sea elegido, solo tienes una oportunidad, piénsalo bien");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 1210, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        jLabel1.setText("ELIGE TU PERSONERO/A");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 730, 50));

        BTcandidato1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/CandidatPersonero.png"))); // NOI18N
        BTcandidato1.setBorderPainted(false);
        BTcandidato1.setContentAreaFilled(false);
        BTcandidato1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTcandidato1.setDefaultCapable(false);
        BTcandidato1.setFocusPainted(false);
        BTcandidato1.setFocusable(false);
        BTcandidato1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/XCandidatPersonero.png"))); // NOI18N
        BTcandidato1.setRequestFocusEnabled(false);
        BTcandidato1.setVerifyInputWhenFocusTarget(false);
        BTcandidato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcandidato1ActionPerformed(evt);
            }
        });
        jPanel1.add(BTcandidato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 190, 190));

        BTcandidato2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/CandidataPersoneria.png"))); // NOI18N
        BTcandidato2.setBorderPainted(false);
        BTcandidato2.setContentAreaFilled(false);
        BTcandidato2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTcandidato2.setFocusPainted(false);
        BTcandidato2.setFocusable(false);
        BTcandidato2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/XCandidataPersoneria.png"))); // NOI18N
        BTcandidato2.setRequestFocusEnabled(false);
        BTcandidato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcandidato2ActionPerformed(evt);
            }
        });
        jPanel1.add(BTcandidato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 200, 190));

        BTcandidato3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/CandidatoPersoneria.png"))); // NOI18N
        BTcandidato3.setBorderPainted(false);
        BTcandidato3.setContentAreaFilled(false);
        BTcandidato3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTcandidato3.setDefaultCapable(false);
        BTcandidato3.setFocusPainted(false);
        BTcandidato3.setFocusable(false);
        BTcandidato3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/ElipseRussmanX.png"))); // NOI18N
        BTcandidato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTcandidato3ActionPerformed(evt);
            }
        });
        jPanel1.add(BTcandidato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 190, 190));

        BTVotoenblanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/VOTO EN BLANCO 23.png"))); // NOI18N
        BTVotoenblanco.setBorderPainted(false);
        BTVotoenblanco.setContentAreaFilled(false);
        BTVotoenblanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTVotoenblanco.setDefaultCapable(false);
        BTVotoenblanco.setFocusable(false);
        BTVotoenblanco.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/XVotoblanco.png"))); // NOI18N
        BTVotoenblanco.setRequestFocusEnabled(false);
        BTVotoenblanco.setVerifyInputWhenFocusTarget(false);
        BTVotoenblanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTVotoenblancoActionPerformed(evt);
            }
        });
        jPanel1.add(BTVotoenblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 190, 180));

        Label_candidato1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_candidato1.setForeground(new java.awt.Color(51, 51, 51));
        Label_candidato1.setText("JUAN NICOLAS ROCHA");
        jPanel1.add(Label_candidato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 320, 40));

        Label_Gradocandidato1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_Gradocandidato1.setForeground(new java.awt.Color(51, 51, 51));
        Label_Gradocandidato1.setText("1103");
        jPanel1.add(Label_Gradocandidato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 60, -1));

        Label_candidato2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_candidato2.setForeground(new java.awt.Color(51, 51, 51));
        Label_candidato2.setText("ANGELA MARIA VELASQUEZ");
        jPanel1.add(Label_candidato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 340, -1));

        Label_Votoenblanco.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_Votoenblanco.setForeground(new java.awt.Color(51, 51, 51));
        Label_Votoenblanco.setText("VOTO EN BLANCO");
        jPanel1.add(Label_Votoenblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 460, 220, -1));

        Label_Gradocandidato2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_Gradocandidato2.setForeground(new java.awt.Color(51, 51, 51));
        Label_Gradocandidato2.setText("1106");
        jPanel1.add(Label_Gradocandidato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 100, -1));

        Label_candidato3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_candidato3.setForeground(new java.awt.Color(51, 51, 51));
        Label_candidato3.setText("RUSSMAN HEREDIA TREJO");
        Label_candidato3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Label_candidato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 340, -1));

        Label_Gradocandidato3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_Gradocandidato3.setForeground(new java.awt.Color(51, 51, 51));
        Label_Gradocandidato3.setText("1105");
        Label_Gradocandidato3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Label_Gradocandidato3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 110, -1));

        Label_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/Fondo950X100 PERSONERO.png"))); // NOI18N
        jPanel1.add(Label_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 950));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTcandidato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcandidato2ActionPerformed
String id= SlectEstudiante.ide1;

int resp = JOptionPane.showConfirmDialog(null, "Está seguro de votar por "+Label_candidato2.getText()+"?");
if (resp==0) {
VP.ActualizarDatos(id, "1");
VP.Voto(id, "1");
BTcandidato1.setEnabled(false);
BTcandidato2.setEnabled(false);
BTcandidato3.setEnabled(false);
BTVotoenblanco.setEnabled(false);

JOptionPane.showMessageDialog(null,"Voto Realizado");
/*Contralor co = new Contralor();
co.setVisible(true);*/
    FIN reiniciar = new FIN();
    
    reiniciar.setVisible(true);
this.setVisible(false);
}
    }//GEN-LAST:event_BTcandidato2ActionPerformed

    private void BTcandidato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcandidato3ActionPerformed
    String id= SlectEstudiante.ide1;

int resp = JOptionPane.showConfirmDialog(null, "Está seguro de votar por "+Label_candidato3.getText()+"?");
if (resp==0) {
VP.ActualizarDatos(id, "1");
VP.Voto(id, "3");
BTcandidato1.setEnabled(false);
BTcandidato2.setEnabled(false);
BTcandidato3.setEnabled(false);
BTVotoenblanco.setEnabled(false);
JOptionPane.showMessageDialog(null,"Voto Realizado");
/*Contralor co = new Contralor();
co.setVisible(true);*/
    FIN reiniciar = new FIN();
    
    reiniciar.setVisible(true);
this.setVisible(false);
}
    }//GEN-LAST:event_BTcandidato3ActionPerformed

    private void BTVotoenblancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTVotoenblancoActionPerformed
    String id= SlectEstudiante.ide1;

int resp = JOptionPane.showConfirmDialog(null, "Está seguro de votar por "+Label_Votoenblanco.getText()+"?");
if (resp==0) {
VP.ActualizarDatos(id, "1");
VP.Voto(id, "6");
BTcandidato1.setEnabled(false);
BTcandidato2.setEnabled(false);
BTcandidato3.setEnabled(false);
BTVotoenblanco.setEnabled(false);
JOptionPane.showMessageDialog(null,"Voto Realizado");
/*Contralor co = new Contralor();

co.setVisible(true);*/

    FIN reiniciar = new FIN();
    
    reiniciar.setVisible(true);
this.setVisible(false);
}    }//GEN-LAST:event_BTVotoenblancoActionPerformed

    
    
    private void BTcandidato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTcandidato1ActionPerformed

        //este codigo see repite en todos los botones cambiando el id del candidato en el metodo "Voto"
        
        
        
String id= SlectEstudiante.ide1; //obtiene el id de la variable publica de la clase selectestudiante

int resp = JOptionPane.showConfirmDialog(null, "Está seguro de votar por "+Label_candidato1.getText()+"?"); //abre cuadro de cofirrmacion confirmando el voto
if (resp==0) { //si dice que si pasa lo siguiente:
VP.ActualizarDatos(id, "1"); //actualiza el estado del estudiante a 1 que signiifca que ya votó
VP.Voto(id, "2"); //crea el voto del estudiante usando su id y el id del candidato


//optimizar el codigo en  un futuro
BTcandidato1.setEnabled(false);
BTcandidato2.setEnabled(false);    //desactiva todos los botones
BTcandidato3.setEnabled(false);
BTVotoenblanco.setEnabled(false);

JOptionPane.showMessageDialog(null,"Voto Realizado"); //ventana emergente confirmando el voto

    FIN reiniciar = new FIN();
    
    reiniciar.setVisible(true);

/*Contralor co = new Contralor();//inicia la ventana contralor
co.setVisible(true); //muestra la ventana contralor*/
this.setVisible(false); //oculta la ventana actual (prsonero)
}

    }//GEN-LAST:event_BTcandidato1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTVotoenblanco;
    private javax.swing.JButton BTcandidato1;
    private javax.swing.JButton BTcandidato2;
    private javax.swing.JButton BTcandidato3;
    private javax.swing.JLabel Label_Fondo;
    private javax.swing.JLabel Label_Gradocandidato1;
    private javax.swing.JLabel Label_Gradocandidato2;
    private javax.swing.JLabel Label_Gradocandidato3;
    private javax.swing.JLabel Label_Votoenblanco;
    private javax.swing.JLabel Label_candidato1;
    private javax.swing.JLabel Label_candidato2;
    private javax.swing.JLabel Label_candidato3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
