/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ConexionSQL.conexion; //paquete de conexion sql
import Datos.Salon; //paquete para consultaar datos de salon sql
import Textos.Textos; //paquete para limitar caracteres
import VOTO.V_Estudiante;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Tecnico Superior
 */
public class SlectEstudiante extends javax.swing.JFrame {
    conexion conn;
    private V_Estudiante VP;
    private Salon SP;
    public SlectEstudiante() {
        
        initComponents();
        this.setLocationRelativeTo(null);
                try {
            this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/icono6.png")).getImage());
        } catch (Exception e) {
        }

        VP= new V_Estudiante();
        SP = new Salon();
         AutoCompleteDecorator.decorate(CB_Salon);
        combobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_nombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Tf_codigo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Label_Grado = new javax.swing.JLabel();
        CB_Salon = new javax.swing.JComboBox();
        BTN_Empezaravotar = new javax.swing.JButton();
        Label_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITEC Votaciones");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_nombre.setBackground(new java.awt.Color(2, 79, 7));
        Label_nombre.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Label_nombre.setForeground(new java.awt.Color(255, 255, 255));
        Label_nombre.setText("Codigo:");
        jPanel1.add(Label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("(puedes escribir tu grado para encontrarlo más rápido)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, -1, -1));

        Tf_codigo.setBackground(new java.awt.Color(255, 255, 255));
        Tf_codigo.setFont(new java.awt.Font("Casper", 0, 24)); // NOI18N
        Tf_codigo.setForeground(new java.awt.Color(153, 153, 153));
        Tf_codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tf_codigo.setBorder(null);
        Tf_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tf_codigoKeyTyped(evt);
            }
        });
        jPanel1.add(Tf_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 180, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 180, 20));

        Label_Grado.setBackground(new java.awt.Color(2, 79, 7));
        Label_Grado.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        Label_Grado.setForeground(new java.awt.Color(255, 255, 255));
        Label_Grado.setText("Salón:");
        jPanel1.add(Label_Grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, 30));

        CB_Salon.setFont(new java.awt.Font("Casper", 1, 18)); // NOI18N
        CB_Salon.setForeground(new java.awt.Color(102, 102, 102));
        CB_Salon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar" }));
        CB_Salon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CB_Salon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_SalonActionPerformed(evt);
            }
        });
        jPanel1.add(CB_Salon, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 180, 30));

        BTN_Empezaravotar.setBackground(new java.awt.Color(0, 51, 0));
        BTN_Empezaravotar.setFont(new java.awt.Font("Casper", 1, 24)); // NOI18N
        BTN_Empezaravotar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Empezaravotar.setText("EMPEZAR A VOTAR");
        BTN_Empezaravotar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(1, 20, 1), null, null));
        BTN_Empezaravotar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_Empezaravotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EmpezaravotarActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_Empezaravotar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 290, 40));

        Label_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personeria/INTERFACES/INGRESO DE DATOS2.jpg"))); // NOI18N
        Label_Fondo.setToolTipText("");
        jPanel1.add(Label_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private  void combobox(){ //trae de sql los datos de salon 
            for (int i = 1; i< 72 ; i++) {
            SP.ObtenerSalon(i);
            CB_Salon.addItem(SP.obtenerTextInfo("Descripción"));
                
        }
    }
    
    //metodo para solo numeros
    private void Tf_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_codigoKeyTyped

        Textos t = new Textos();
        t.Snumeros(evt);
        
        

    }//GEN-LAST:event_Tf_codigoKeyTyped

    private void CB_SalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_SalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_SalonActionPerformed

    private void BTN_EmpezaravotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EmpezaravotarActionPerformed
              System.out.println("Codigo es :"  +Tf_codigo.getText());

        if ("".equals(Tf_codigo.getText())||CB_Salon.getSelectedItem()=="Seleccionar") {   //VALIDAR QUE SE HAYAN RELLENADO LOS CAMPOS
            JOptionPane.showMessageDialog(null, "Por favor Seleccione y rellene todos los campos"); //en caso de que no, envía un mensaje
        }else{ //si se han rellenado los campos :
        
   VP.ObtenerDatos(Tf_codigo.getText(),CB_Salon.getSelectedIndex()) ;  //sacamos el codigodel estudiante de TF y el index de el CB 
                                                                       //y le damos en obtener informacion
   String E= VP.obtenerTextInfo("Estado");          //una ve identificado el estudiante, se obtiene su estado (si ha votado o no)                   
    System.out.println("EESTADO DE EL ESTUDIANTE:"+E);  //nos lo muestra en la consola

        


   String Nombre= VP.obtenerTextInfo("ApellidoNombre"); //obtenemos y guardamos en la variable "Nombre" el nombre del estudiante
   ide1= VP.obtenerTextInfo("IDEstudiante"); //obtenemos y guardamos en una variable publica el id del estudiante
  
   
   System.out.println("id:"+ide1); //nos imprime el id del estudiante en la consola
    
int resp = JOptionPane.showConfirmDialog(null, "Es Usted: "+Nombre+" ?"); //nos muestra un cuadro de confirmacion preguntando si somo ese estudiante 
        
        if (resp==0) { //si el estudiante le da en la ventada "si" el valor es 0 y si pasa eso hace lo siguente:
                       
        Personero ITH = new Personero(); //crea la vntana de personero
        if ("0".equals(E)) { //confrmamos el estado, si la variable está en 0 significa que no ha votado y continua:
         System.out.println("EL ESTUDIANTE NO HA VOTADO"); //nos imprime en la consola
        ITH.setVisible(true); //nos muestra la ventana del personero
        ITH.setResizable(false); //hace que la vetana no se pueda cambiar el tamaño
        
        this.setVisible(false); //hace que la ventana actual (seleccionar estudiante) se oculte
        }else{ //si la variable es difierente de 0 o sea 1 significa que el estudiante ya ha votado y hará lo sosiguente:
        JOptionPane.showMessageDialog(null,"Lo siento Usted ya ha votado!"); //mostrar una ventana diciendo que el estudiante ya ha votado
        }
       
        }
        }  
        
        
        
        
    }//GEN-LAST:event_BTN_EmpezaravotarActionPerformed
public static String ide1; //variable publica del ide

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlectEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlectEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlectEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlectEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                
                new SlectEstudiante().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Empezaravotar;
    private javax.swing.JComboBox CB_Salon;
    private javax.swing.JLabel Label_Fondo;
    private javax.swing.JLabel Label_Grado;
    private javax.swing.JLabel Label_nombre;
    private javax.swing.JTextField Tf_codigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
